### ISSUE TITLE
store missing

### ISSUE THREAD

**Issue by andywong39** [cukikt0302/vue-simple-table#1]
Hello @cukikt0302! Very good job!

I have a favor. can you also add source code of this store and event handlers? Currently, we only have dist/build.js.

**Comment by cukikt0302** [comment]
Yes i will do it in next week.

**Comment by andywong39** [comment]
can you just add your previous work on stores? I have urgent need of vue table components. Thanks :)

**Comment by cukikt0302** [comment]
[table.vue](https://github.com/cukikt0302/vue-simple-table/blob/master/table.vue)
In this **table.vue** contain two other component:
[vue-context-menu](https://github.com/vmaimone/vue-context-menu)
[uiv](https://github.com/wxsms)

**Comment by andywong39** [comment]
what was build.js for? can we have source code of it? and how did you bundle it? using webpack?

**Comment by cukikt0302** [comment]
Build.js is contain my admin (Vue + Jquery + Adminlte)
Yes, i use webpack

**Comment by andywong39** [comment]
can I run sample without dist.js?

**Comment by cukikt0302** [comment]
install and (import or require) 2 package with npm: 
[vue-context-menu](https://github.com/vmaimone/vue-context-menu)
[uiv](https://github.com/wxsms)
and import [table.vue](https://github.com/cukikt0302/vue-simple-table/blob/master/table.vue)

finish woth my full example [full example](https://github.com/cukikt0302/vue-simple-table/blob/master/general.vue)

**Comment by andywong39** [comment]
done. this.emit('edit_row'...) where do we handle this event?

**Comment by cukikt0302** [comment]
[full example](https://github.com/cukikt0302/vue-simple-table/blob/master/general.vue)

**line 359 -> 363**

In component use table.vue 

```
methods: {
 edit_row(row) {
   console.log(row)
 }
}
```

**Comment by cukikt0302** [comment]
Has it worked?

**Comment by andywong39** [comment]
It's worked.What if a field in data JSON is JSON object? I want to show show only its one field, not entire json,

e.g .

data:{
{id:1, name:'xx', profile:{name:xxx,age:xx}}...}

I want to show profilename for profile field.

**Comment by cukikt0302** [comment]
Oop table.vue just each data level 1

**Comment by andywong39** [comment]
I know, no worries, I will customize it.

**Comment by andywong39** [comment]
In general, we have this.$store.commit('set_page_header',...), what's this for?

In pagination, we have this.$emit('curren_page',) is this fully functional?

**Comment by cukikt0302** [comment]
this.$store.commit('set_page_header',...) Its set title for Vue-router, skip it
this.$emit('curren_page',) in methods: {current_page(num) { this.action.pagination.current_page = num }}

**Comment by cukikt0302** [comment]
(remove or comment) it in [general.vue](https://github.com/cukikt0302/vue-simple-table/blob/master/general.vue) 316 -> 319

**Comment by andywong39** [comment]
OK.

**Comment by cukikt0302** [comment]
are you finished?
If there's a problem, I'll continue tomorrow

**Comment by andywong39** [comment]
Another error. when I click column to inline edit, I get error 'Failed to resolve directive: focus'

**Comment by cukikt0302** [comment]
After import Vue
Need register two directive
Vue.directive('focus', { inserted(el) { el.focus() } })
Vue.directive('selected', { inserted(el) { el.select() } })\
This 2 directive is just to work on the input.
If not need you can remove v-focus end v-selected attribute in element

**Comment by andywong39** [comment]
ok that error is gone but inline-edit is not working. ;(

**Comment by cukikt0302** [comment]
can i view it?
image teamviewer, ....

**Comment by cukikt0302** [comment]
show me console

**Comment by andywong39** [comment]
No errors, just not working, FYI, I replaced all `r` with `rowIndex`, is this a problem?

**Comment by cukikt0302** [comment]
Do not change what I tried to change a few times with r and c but it was not working.
You should leave the default bug problem, I will get out.

**Comment by andywong39** [comment]
oops, is this not your own code?

**Comment by cukikt0302** [comment]
It is the code of i I have been try to change 1 several times to easy visible than
Now it is working fine with no errors

**Comment by cukikt0302** [comment]
Give me your code
I will try on my machine

**Comment by andywong39** [comment]
hello @cukikt0302 , in table.vue, we emit 'edit_row', can we capture this in either general.vue? 

So this is parent<>direct child event communication. this is really important when we have several tables.

**Comment by andywong39** [comment]
@cukikt0302  how do you connect pagination and table data?

**Comment by cukikt0302** [comment]
when we have several tables.
On component <my-table @edit_row="You function() in methods {}"></my-table>

https://vuejs.org/v2/guide/computed.html#Computed-vs-Watched-Property
watch current_page and using ajax

**Comment by andywong39** [comment]
what is @edit_row is for? And can't we get total_page automatically?

**Comment by cukikt0302** [comment]
when we have several tables. 
<my-table @edit_row="your_method1">
<my-table @edit_row="your_method2">
<my-table @edit_row="your_method3">

**Comment by andywong39** [comment]
@edit_row is prop?

**Comment by cukikt0302** [comment]
@edit_row is a event will access to method in your current component

**Comment by cukikt0302** [comment]
ex: current component general.vue. we have 2 methods: 

```
methods: {
  abc(row) {
    console.log(row) 
  },

  other_method(row) {
    console.log(row)
  }
}
```

<my-table @edit_row="abc"></my-table>
<my-table @edit_row="other_method"></my-table>

**Comment by cukikt0302** [comment]
i'm writing document

**Comment by cukikt0302** [comment]
update basic document
